export const dataSlides = [
  {
    id: 1,
    title: "Sorio",
    path: "sorio/compress",
    children: [
      {
        id: 1,
        path: "sorio",
        image: "sorio (1).jpg",
        title: "Sorio",
      },
      {
        id: 2,
        path: "sorio",
        image: "sorio (2).jpg",
        title: "Sorio",
      },
      {
        id: 3,
        path: "sorio",
        image: "sorio (3).jpg",
        title: "Sorio",
      },
      {
        id: 4,
        path: "sorio",
        image: "sorio (4).jpg",
        title: "Sorio",
      },
      {
        id: 5,
        path: "sorio",
        image: "sorio (5).jpg",
        title: "Sorio",
      },
      {
        id: 6,
        path: "sorio",
        image: "sorio (6).jpg",
        title: "Sorio",
      },
      {
        id: 7,
        path: "sorio",
        image: "sorio (7).jpg",
        title: "Sorio",
      },
      {
        id: 8,
        path: "sorio",
        image: "sorio (8).jpg",
        title: "Sorio",
      },
      {
        id: 9,
        path: "sorio",
        image: "sorio (9).jpg",
        title: "Sorio",
      },
      {
        id: 10,
        path: "sorio",
        image: "sorio (10).jpg",
        title: "Sorio",
      },
      {
        id: 11,
        path: "sorio",
        image: "sorio (11).jpg",
        title: "Sorio",
      },
      {
        id: 12,
        path: "sorio",
        image: "sorio (12).jpg",
        title: "Sorio",
      },
      {
        id: 13,
        path: "sorio",
        image: "sorio (13).jpg",
        title: "Sorio",
      },
      {
        id: 14,
        path: "sorio",
        image: "sorio (14).jpg",
        title: "Sorio",
      },
      {
        id: 15,
        path: "sorio",
        image: "sorio (15).jpg",
        title: "Sorio",
      },
    ],
  },
  {
    id: 2,
    title: "Arucas",
    path: "arucas/compress",
    children: [
      {
        id: 1,
        path: "arucas",
        image: "arucas (1).jpg",
        title: "arucas",
      },
      {
        id: 2,
        path: "arucas",
        image: "arucas (2).jpg",
        title: "arucas",
      },
      {
        id: 3,
        path: "arucas",
        image: "arucas (3).jpg",
        title: "arucas",
      },
      {
        id: 4,
        path: "arucas",
        image: "arucas (4).jpg",
        title: "arucas",
      },
      {
        id: 5,
        path: "arucas",
        image: "arucas (5).jpg",
        title: "arucas",
      },
      {
        id: 6,
        path: "arucas",
        image: "arucas (6).jpg",
        title: "arucas",
      },
      {
        id: 7,
        path: "arucas",
        image: "arucas (7).jpg",
        title: "arucas",
      },
      {
        id: 8,
        path: "arucas",
        image: "arucas (8).jpg",
        title: "arucas",
      },
      {
        id: 9,
        path: "arucas",
        image: "arucas (9).jpg",
        title: "arucas",
      },
      {
        id: 10,
        path: "arucas",
        image: "arucas (10).jpg",
        title: "arucas",
      },
      {
        id: 11,
        path: "arucas",
        image: "arucas (11).jpg",
        title: "arucas",
      },
      {
        id: 12,
        path: "arucas",
        image: "arucas (12).jpg",
        title: "arucas",
      },
      {
        id: 13,
        path: "arucas",
        image: "arucas (13).jpg",
        title: "arucas",
      },
      {
        id: 14,
        path: "arucas",
        image: "arucas (14).jpg",
        title: "arucas",
      },
      {
        id: 15,
        path: "arucas",
        image: "arucas (15).jpg",
        title: "arucas",
      },
      {
        id: 16,
        path: "arucas",
        image: "arucas (16).jpg",
        title: "arucas",
      },
      {
        id: 17,
        path: "arucas",
        image: "arucas (17).jpg",
        title: "arucas",
      },
      {
        id: 18,
        path: "arucas",
        image: "arucas (18).jpg",
        title: "arucas",
      },
      {
        id: 19,
        path: "arucas",
        image: "arucas (19).jpg",
        title: "arucas",
      },
      {
        id: 20,
        path: "arucas",
        image: "arucas (20).jpg",
        title: "arucas",
      },
      {
        id: 21,
        path: "arucas",
        image: "arucas (21).jpg",
        title: "arucas",
      },
      {
        id: 22,
        path: "arucas",
        image: "arucas (22).jpg",
        title: "arucas",
      },
      {
        id: 23,
        path: "arucas",
        image: "arucas (23).jpg",
        title: "arucas",
      },
      {
        id: 24,
        path: "arucas",
        image: "arucas (24).jpg",
        title: "arucas",
      },
    ],
  },
  {
    id: 3,
    title: "Los Tilos de Moya",
    path: "lostilos/compress",
    children: [
      {
        id: 1,
        path: "lostilos",
        image: "lostilos (1).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 2,
        path: "lostilos",
        image: "lostilos (2).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 3,
        path: "lostilos",
        image: "lostilos (3).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 4,
        path: "lostilos",
        image: "lostilos (4).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 5,
        path: "lostilos",
        image: "lostilos (5).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 6,
        path: "lostilos",
        image: "lostilos (6).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 7,
        path: "lostilos",
        image: "lostilos (7).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 8,
        path: "lostilos",
        image: "lostilos (8).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 9,
        path: "lostilos",
        image: "lostilos (9).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 10,
        path: "lostilos",
        image: "lostilos (10).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 11,
        path: "lostilos",
        image: "lostilos (11).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 12,
        path: "lostilos",
        image: "lostilos (12).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 13,
        path: "lostilos",
        image: "lostilos (13).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 14,
        path: "lostilos",
        image: "lostilos (14).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 15,
        path: "lostilos",
        image: "lostilos (15).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 16,
        path: "lostilos",
        image: "lostilos (16).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 17,
        path: "lostilos",
        image: "lostilos (17).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 18,
        path: "lostilos",
        image: "lostilos (18).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 19,
        path: "lostilos",
        image: "lostilos (19).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 20,
        path: "lostilos",
        image: "lostilos (20).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 21,
        path: "lostilos",
        image: "lostilos (21).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 22,
        path: "lostilos",
        image: "lostilos (22).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 23,
        path: "lostilos",
        image: "lostilos (23).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 24,
        path: "lostilos",
        image: "lostilos (24).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 25,
        path: "lostilos",
        image: "lostilos (25).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 26,
        path: "lostilos",
        image: "lostilos (26).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 27,
        path: "lostilos",
        image: "lostilos (27).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 28,
        path: "lostilos",
        image: "lostilos (28).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 29,
        path: "lostilos",
        image: "lostilos (29).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 30,
        path: "lostilos",
        image: "lostilos (30).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 31,
        path: "lostilos",
        image: "lostilos (31).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 32,
        path: "lostilos",
        image: "lostilos (32).jpg",
        title: "Los Tilos de Moya",
      },
      {
        id: 33,
        path: "lostilos",
        image: "lostilos (33).jpg",
        title: "Los Tilos de Moya",
      },
    ],
  },
  {
    id: 4,
    title: "Roque Nublo",
    path: "roquenublo/compress",
    children: [
      {
        id: 1,
        path: "roquenublo",
        image: "roquenublo (1).jpg",
        title: "Roque Nublo",
      },
      {
        id: 2,
        path: "roquenublo",
        image: "roquenublo (2).jpg",
        title: "Roque Nublo",
      },
      {
        id: 3,
        path: "roquenublo",
        image: "roquenublo (3).jpg",
        title: "Roque Nublo",
      },
      {
        id: 4,
        path: "roquenublo",
        image: "roquenublo (4).jpg",
        title: "Roque Nublo",
      },
      {
        id: 5,
        path: "roquenublo",
        image: "roquenublo (5).jpg",
        title: "Roque Nublo",
      },
      {
        id: 6,
        path: "roquenublo",
        image: "roquenublo (6).jpg",
        title: "Roque Nublo",
      },
      {
        id: 7,
        path: "roquenublo",
        image: "roquenublo (7).jpg",
        title: "Roque Nublo",
      },
      {
        id: 8,
        path: "roquenublo",
        image: "roquenublo (8).jpg",
        title: "Roque Nublo",
      },
      {
        id: 9,
        path: "roquenublo",
        image: "roquenublo (9).jpg",
        title: "Roque Nublo",
      },
      {
        id: 10,
        path: "roquenublo",
        image: "roquenublo (10).jpg",
        title: "Roque Nublo",
      },
      {
        id: 11,
        path: "roquenublo",
        image: "roquenublo (11).jpg",
        title: "Roque Nublo",
      },
      {
        id: 12,
        path: "roquenublo",
        image: "roquenublo (12).jpg",
        title: "Roque Nublo",
      },
      {
        id: 13,
        path: "roquenublo",
        image: "roquenublo (13).jpg",
        title: "Roque Nublo",
      },
      {
        id: 14,
        path: "roquenublo",
        image: "roquenublo (14).jpg",
        title: "Roque Nublo",
      },
      {
        id: 15,
        path: "roquenublo",
        image: "roquenublo (15).jpg",
        title: "Roque Nublo",
      },
      {
        id: 16,
        path: "roquenublo",
        image: "roquenublo (16).jpg",
        title: "Roque Nublo",
      },
      {
        id: 17,
        path: "roquenublo",
        image: "roquenublo (17).jpg",
        title: "Roque Nublo",
      },
      {
        id: 18,
        path: "roquenublo",
        image: "roquenublo (18).jpg",
        title: "Roque Nublo",
      },
      {
        id: 19,
        path: "roquenublo",
        image: "roquenublo (19).jpg",
        title: "Roque Nublo",
      },
      {
        id: 20,
        path: "roquenublo",
        image: "roquenublo (20).jpg",
        title: "Roque Nublo",
      },
      {
        id: 21,
        path: "roquenublo",
        image: "roquenublo (21).jpg",
        title: "Roque Nublo",
      },
      {
        id: 22,
        path: "roquenublo",
        image: "roquenublo (22).jpg",
        title: "Roque Nublo",
      },
      {
        id: 23,
        path: "roquenublo",
        image: "roquenublo (23).jpg",
        title: "Roque Nublo",
      },
      {
        id: 24,
        path: "roquenublo",
        image: "roquenublo (24).jpg",
        title: "Roque Nublo",
      },
    ],
  },
  {
    id: 5,
    title: "Moya",
    path: "moya/compress",
    children: [
      {
        id: 1,
        path: "moya",
        image: "moya (1).jpg",
        title: "Moya",
      },
      {
        id: 2,
        path: "moya",
        image: "moya (2).jpg",
        title: "Moya",
      },
      {
        id: 3,
        path: "moya",
        image: "moya (3).jpg",
        title: "Moya",
      },
      {
        id: 4,
        path: "moya",
        image: "moya (4).jpg",
        title: "Moya",
      },
      {
        id: 5,
        path: "moya",
        image: "moya (5).jpg",
        title: "Moya",
      },
      {
        id: 6,
        path: "moya",
        image: "moya (6).jpg",
        title: "Moya",
      },
      {
        id: 7,
        path: "moya",
        image: "moya (7).jpg",
        title: "Moya",
      },
      {
        id: 8,
        path: "moya",
        image: "moya (8).jpg",
        title: "Moya",
      },
      {
        id: 9,
        path: "moya",
        image: "moya (9).jpg",
        title: "Moya",
      },
      {
        id: 10,
        path: "moya",
        image: "moya (10).jpg",
        title: "Moya",
      },
    ],
  },
  {
    id: 6,
    title: "El Charco Azul",
    path: "charcoazul/compress",
    children: [
      {
        id: 1,
        path: "charcoazul",
        image: "charcoazul (1).jpg",
        title: "El Charco Azul",
      },
      {
        id: 2,
        path: "charcoazul",
        image: "charcoazul (2).jpg",
        title: "El Charco Azul",
      },
      {
        id: 3,
        path: "charcoazul",
        image: "charcoazul (3).jpg",
        title: "El Charco Azul",
      },
      {
        id: 4,
        path: "charcoazul",
        image: "charcoazul (4).jpg",
        title: "El Charco Azul",
      },
      {
        id: 5,
        path: "charcoazul",
        image: "charcoazul (5).jpg",
        title: "El Charco Azul",
      },
      {
        id: 6,
        path: "charcoazul",
        image: "charcoazul (6).jpg",
        title: "El Charco Azul",
      },
      {
        id: 7,
        path: "charcoazul",
        image: "charcoazul (7).jpg",
        title: "El Charco Azul",
      },
      {
        id: 8,
        path: "charcoazul",
        image: "charcoazul (8).jpg",
        title: "El Charco Azul",
      },
      {
        id: 9,
        path: "charcoazul",
        image: "charcoazul (9).jpg",
        title: "El Charco Azul",
      },
      {
        id: 10,
        path: "charcoazul",
        image: "charcoazul (10).jpg",
        title: "El Charco Azul",
      },
      {
        id: 11,
        path: "charcoazul",
        image: "charcoazul (11).jpg",
        title: "El Charco Azul",
      },
    ],
  },
  {
    id: 7,
    title: "El Pico De Nieve",
    path: "picodenieve/compress",
    children: [
      {
        id: 1,
        path: "picodenieve",
        image: "picodenieve (1).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 2,
        path: "picodenieve",
        image: "picodenieve (2).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 3,
        path: "picodenieve",
        image: "picodenieve (3).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 4,
        path: "picodenieve",
        image: "picodenieve (4).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 5,
        path: "picodenieve",
        image: "picodenieve (5).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 6,
        path: "picodenieve",
        image: "picodenieve (6).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 7,
        path: "picodenieve",
        image: "picodenieve (7).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 8,
        path: "picodenieve",
        image: "picodenieve (8).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 9,
        path: "picodenieve",
        image: "picodenieve (9).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 10,
        path: "picodenieve",
        image: "picodenieve (10).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 11,
        path: "picodenieve",
        image: "picodenieve (11).jpg",
        title: "El Pico De Nieve",
      },
      {
        id: 12,
        path: "picodenieve",
        image: "picodenieve (12).jpg",
        title: "El Pico De Nieve",
      },
    ],
  },
];